title: Nation i Lund
description: Find out what's happening at the student nations in Lund tonight!

head:
  -
    [ meta, { property: "og:image", content: "https://nationilund.se/logo.png" } ]
  -
    [ meta, { name: "twitter:image:src", content: "https://nationilund.se/logo.png" } ]
  -
    [ meta, { itemprop: "image", content: "https://nationilund.se/logo.png" } ]

markdown:
  anchor:
    permalink: false
  externalLinks:
    target: ''
    rel: noopener noreferrer

themeConfig:
  logo: logo.svg
  nav:
    -
      text: API
      link: /api.md
    -
      text: About
      link: /about.md
